---
title: 'R Course: Lesson 2: LINEAR REGRESSION'
author: "Reddy Lee"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(ggplot2)
```

# Math
$$ y_i=a+bx_i+e_i$$
## example 1
```{r}
attach(ChickWeight)
summary(lm(weight~Time))
```
## example
```{r}
data_lesson <- read.csv("rcourse_lesson1_data.txt",sep = "\t")
categorical.lm <- lm(rt~type,data=data_lesson)
head(resid(categorical.lm))
```



# Data Cleaning
```{r}
library(babynames)
View(babynames)
```
 
```{r}

data_Lee <- babynames %>% 
  filter(name=="Lee")

xtabs(~name,data_Lee)
```
```{r}
data_clean <- babynames %>% 
  filter(name=="Page") %>% 
  mutate(name=factor(name)) %>% 
  filter(year>1900 & year<=2000)

xtabs(~name,data_clean)

summary(data_clean$year)
```
# Describe the data by Figures
```{r}
data_figs <- data_clean %>% 
  mutate(sex=factor(sex,levels=c("F","M"),labels=c("Female","Male")))
Lee.plot <- data_Lee %>% 
  ggplot(aes(x=log10(prop)))+
  geom_histogram(color="skyblue")
Page.plot <- data_figs %>% 
  ggplot(aes(x=log10(prop)))+
  geom_histogram(color="skyblue")

Lee.plot
Page.plot
```
## time effect
```{r}
year.plot <- data_figs %>% 
  ggplot(aes(x=year,y=log10(prop)))+
  geom_point()+
  geom_smooth(method = "lm")+
  ggtitle("Proportion of people with name 'Page' over time")+
  xlab("Year")+
  ylab("Proportion of people(log)")+
  theme_classic()+
  theme(text=element_text(size=14),title=element_text(size=16))

year.plot
```
## gender effect
```{r}
sex.plot <- data_figs %>% 
  ggplot(aes(x=sex,y=log10(prop)))+
  geom_boxplot(aes(fill=sex))+
  ggtitle("Proportion of People with the Name 'Page' By Sex")+
  xlab("Gender")+
  ylab("Proportion of People\n(log base 10 transformed)")+
  theme_classic()+
  theme(text=element_text(size=14),
        title=element_text(size=16),
        legend.position="none", legend.key=element_blank())

sex.plot
```
# Statistics analysis
## Continuous Predictor: Does your name get more or less popular between the years of 1901 and 2000?
```{r}
library(stargazer)
data.stats <- data_clean
attach(data.stats)

year.lm <- lm(log10(prop)~year)
summary(year.lm)
stargazer(year.lm,type="text")
hist( resid(year.lm))
```

## Categorical Predictor: Is your name more or less popular with females or males?
```{r}
sex.lm <- lm(log10(prop)~sex)
summary(sex.lm)
stargazer(year.lm, sex.lm,type="text")
hist( resid(sex.lm))
```

