---
title: 'R Course: Lesson 6: Linear Mixed Effects Models (LMEM)'
author: "Reddy Lee"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,warning = F,message = F)
library(tidyverse)
library(patchwork)
library(gapminder)
library(forcats)
library(stargazer)
library(purrr)
library(lme4)
```

# Math
$$ y_i=a+b_1x_{1i}+b_2x_{2i}+b_1x_{1i}*b_2x_{2i}+e_i$$
$$ y_i=a+a_s+a_y+b_1x_{1i}+b_2x_{2i}+b_1x_{1i}*b_2x_{2i}+e_i$$
## example in R with Chickweight
```{r}
elections <- read.csv("data5/rcourse_lesson5_data_elections.txt",sep="\t")
states <- read.csv("data5/rcourse_lesson5_data_states.txt",sep="\t")
results <- list.files(path="data5/elections",full.names = T) %>% 
  map(read.table,header=T,sep="\t") %>% 
  reduce(rbind)

data.clean <- results %>% 
  inner_join(elections) %>% 
  inner_join(states) %>% 
  mutate(state=factor(state))

model.election <- lmer(perc_votes_incumbent~incumbent_party*civil_war+
                         (1|state)+(1|year),data = data.clean)

summary(model.election)
```
## Math 2
$$ y_i=a+a_s+a_y+(b_{s1}+b_1)x_{1i}+(b_{y1}+b_2)x_{2i}+b_1x_{1i}*b_2x_{2i}+e_i$$
```{r}
model.election2 <- lmer(perc_votes_incumbent~incumbent_party*civil_war+
                         (1+incumbent_party|state)+(1+civil_war|year),data = data.clean)

summary(model.election2)
```
# Data cleaning
```{r}
data_results <- list.files(path = "data6/results",full.names = T) %>% 
  map(read.table,header=T,sep="\t") %>% 
  reduce(rbind)

data.subjects <- read.csv("data6/rcourse_lesson6_data_subjects.txt", header=T, sep="\t")

data.items <- read.csv("data6/rcourse_lesson6_data_items.txt", header=T, sep="\t")

```

```{r}
data.clean <- data_results %>% 
  rename(trial_number=SimpleRTBLock.TrialNr.,
         correct_response=StroopItem.CRESP.,
         given_response=StroopItem.RESP.,
         accuracy=StroopItem.ACC.,
         rt=StroopItem.RT.) %>% 
  select(subject_id,block,item,trial_number,Congruency,correct_response,given_response,accuracy,rt) %>% 
  inner_join(data.subjects) %>% 
  inner_join(data.items) %>% 
  mutate(half=ifelse(block=="one"|block=="two","first","second")) %>% 
  view()

data.rt.sum <- data.clean %>% 
  group_by(subject_id,Congruency,half) %>% 
  summarise(rt_mean=mean(rt),rt_sd=sd(rt)) %>% 
  ungroup %>% 
  mutate(rt_high=rt_mean+(2*rt_sd),
         rt_low=rt_mean+(2*rt_sd)) %>% 
  view()
```
```{r}
data.accuracy.clean <- data.clean %>% 
  inner_join(data.rt.sum) %>% 
  filter(rt<rt_high|rt>rt_low) %>% 
  view()

data.rt.clean <- data.accuracy.clean %>% 
  filter(accuracy=="1")
```

# Figures
```{r}
library(RColorBrewer)
```

```{r}
data.accuracy.figs <- data.accuracy.clean %>% 
  group_by(subject_id,congruency,half) %>% 
  summarise(perc_correct=mean(accuracy)*100) %>% 
  ungroup() %>% 
  mutate(congruency=factor(congruency,levels=c("con","incon"),labels=c("congruent","incongruent")))

view(data.accuracy.figs)

accuracy.plot <- data.accuracy.figs %>%
  ggplot(aes(x=half,y=perc_correct,fill=congruency))+
  geom_boxplot()+
  ylim(0,100)+
  geom_hline(yintercept = 50)+
  scale_fill_manual(values=c(col.con,col.incon))
accuracy.plot

cols <- brewer.pal(5,"PuOr")
col.con <- cols[1]
col.incon <- cols[5]
```
```{r}
data.rt.figs <- data.rt.clean %>% 
  mutate(congruency=factor(congruency,levels=c("con","incon"),
                           labels=c("congruent","incongruent")))

rt.histogram.plot <- data.rt.figs %>% 
  ggplot(aes(x=rt,fill=congruency))+
  geom_histogram(bins = 30)+
  facet_grid(half~congruency)+
  scale_fill_manual(values = c(col.con,col.incon))

rt.histogram.plot
```
```{r}
data.rt.clean <- data.accuracy.clean %>% 
  filter(accuracy=="1") %>% 
  mutate(rt.log10=log10(rt))

rt.log10.histogram.plot <- data.rt.clean %>% 
  ggplot(aes(x=rt.log10,fill=congruency))+
  geom_histogram(bins = 40)+
  facet_grid(half~congruency)+
  scale_fill_manual(values=c(col.con,col.incon))
rt.log10.histogram.plot
```
```{r}
data.rt.figs = data.rt.clean %>%
                filter(accuracy == "1") %>%
                mutate(rt_log10 = log10(rt))

rt.log10.boxplot.plot <- data.rt.figs %>% 
  ggplot(aes(x=half,y=rt.log10,fill=congruency))+
  geom_boxplot()+
  scale_fill_manual(values=c(col.con,col.incon))

rt.log10.boxplot.plot
```
# Statistics
```{r}
data.accuracy.stats <- data.accuracy.clean
xtabs(~subject_id+congruency+half,data = data.accuracy.stats)  
xtabs(~item+congruency+half,data = data.accuracy.stats)  
xtabs(~item+half,data = data.accuracy.stats)
```
## unconverged model
```{r}
accuracy.glmer <- data.accuracy.stats %>% 
  glmer(accuracy~congruency*half+(1+congruency*half|subject_id)+(1+half|item),family = "binomial",data=.)
summary(accuracy.glmer)
```
Note: The model fails to converge in 10000 evaluations

## converged model
```{r}
accuracy.glmer.1 <- data.accuracy.stats %>% 
    glmer(accuracy~congruency*half+(1|subject_id)+(0+half|subject_id)+(1|item),family = "binomial",data=.)
summary(accuracy.glmer.1)
```
```{r}
data.rt.stats <- data.rt.clean
rt.log10.lmer <- data.rt.stats %>% 
  lmer(rt.log10~congruency*half+(1+congruency*half|subject_id)+(1+half|item),data=.)
summary(rt.log10.lmer)
```

